### ISSUE TITLE
Suddenly Stopped Working

### ISSUE THREAD

**Issue by ghost** [enewe101/corenlpy#1]
This package worked fine circa 01/26/19.
Now it quits immediately with message:
```
Traceback (most recent call last):
  File "C:\Users\user/filePath\Break_Clauses.py", line 3, in <module>
    import corenlpy
  File "C:\Users\user/filePath\corenlpy\__init__.py", line 1, in <module>
    from corenlp_xml_reader.annotated_text import AnnotatedText, Token, Sentence
  File "C:\Users\user/filePath\corenlp_xml_reader\__init__.py", line 1, in <module>
    from annotated_text import AnnotatedText, Token, Sentence
ModuleNotFoundError: No module named 'annotated_text'
```

**Comment by enewe101** [comment]
There have been no changes in the last month, so I'd suspect something wrong with your environment.  Try reinstalling in a new virtualenv to see if that helps.  If so, try ununstallingand reinstalling in your working environment.  Let me know what happens!

**Comment by tnusser** [comment]
I have the same issue as @AlexGolf18 
Seems to be an issue with python version 3.6+
